global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'barterly-backend'
    static_configs:
      - targets: ['host.docker.internal:3000']
        # Use 'backend:5000' if running in Docker Compose